inherit_from: configs/256res/ffhq_256.yaml
training:
  out_dir:  out/ffhq256_pretrained
test:
  model_file: Giraffe-weights/checkpoint_ffhq256-fa488759.pt
rendering:
  render_dir: rendering
  render_program: ['vis_raw_nerf']